learning_log/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include,url

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'', include(('learning_logs.urls', "learning_logs"), namespace="learning_logs")),
    url(r'^users/',include(('users.urls','users'),namespace = "users")),
]

learning_logs/urls.py
from django.conf.urls import url
from . import views
urlpatterns = [
    url (r'^$',views.index,name='index'),
    url(r'^topics/$',views.topics,name='topics'),
    url(r'^topics/(?P<topic_id>\d+)/$',views.topic,name='topic'),
    url(r'^new_topic/$',views.new_topic,name='new_topic'),
    url(r'^new_entry/(?P<topic_id>\d+)/$', views.new_entry, name='new_entry'),
    url(r'^edit_entry/(?P<entry_id>\d+)/$',views.edit_entry,name='edit_entry')

 ]

users/urls.py
from django.conf.urls import url
from django.contrib.auth.views import LoginView
from . import views
urlpatterns = [
    url(r'^login/$',LoginView.as_view(template_name='users/login.html'),name='login'),
    url(r'^logout/$',views.logout_view,name='logout'),
    url(r'^register/$',views.register,name='register')
]

learning_logs/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Topic(models.Model):
    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User,on_delete=models.CASCADE)
    def __str__(self):
        return self.text

class Entry(models.Model):
    topic = models.ForeignKey(Topic,on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = "entries"

    def __str__(self):
        return  self.text[:50] + "..."

users/models.py
from django.db import models

# Create your models here.

learning_logs/forms.py
from django import forms
from .models import Topic,Entry
class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ['text']
        labels = {'text': ''}

class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['text']
        labels = {'text':''}
        widgets = {'text':forms.Textarea(attrs={'cols':80})}

learning_logs/views.py
from django.shortcuts import render
from .models import Topic,Entry
from django.http import HttpResponseRedirect
from .forms import TopicForm,EntryForm
from django.urls import reverse
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect,Http404
from django.shortcuts import render,get_object_or_404
# Create your views here.
def index(request):
    return render(request,'learning_logs/index.html')
@login_required
def topics(request):
    topics = Topic.objects.filter(owner = request.user).order_by('date_added')
    context = {'topics':topics}
    return render(request,'learning_logs/topics.html',context)
@login_required
def topic(request,topic_id):
    topic = get_object_or_404(Topic,id = topic_id)
    if topic.owner != request.user:
        raise Http404
    entries = topic.entry_set.order_by('-date_added')
    context = {'topic':topic,'entries':entries}
    return render(request,'learning_logs/topic.html',context)
@login_required
def new_topic(request):
    if request.method != 'POST':
        form = TopicForm()
    else:
        form = TopicForm(request.POST)
        if form.is_valid():
            new_topic = form.save(commit=False)
            new_topic.owner = request.user
            new_topic.save()
            return HttpResponseRedirect(reverse('learning_logs:topics'))

    context = {'form':form}
    return render(request,'learning_logs/new_topic.html',context)
@login_required

def new_entry(request,topic_id):
    topic = Topic.objects.get(id = topic_id)
    if request.method != 'POST':
        form = EntryForm()
    else:
        form = EntryForm(data = request.POST)
        if form.is_valid():
            new_entry = form.save(commit = False)
            new_entry.topic = topic
            new_entry.save()
            return HttpResponseRedirect(reverse('learning_logs:topic',args=[topic_id]))

    context = {'topic':topic,'form':form}
    return render(request,'learning_logs/new_entry.html',context)
@login_required
def edit_entry(request,entry_id):
    entry = Entry.objects.get(id = entry_id)
    topic = entry.topic
    if topic.owner != request.user:
        raise Http404
    if request.method != 'POST':
        form = EntryForm(instance=entry)
    else:
        form = EntryForm(instance=entry,data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('learning_logs:topic',args=[topic.id]))

    context = {'topic':topic,'form':form}
    return render(request,'learning_logs/edit_entry.html',context)
@login_required
def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse('learning_logs:index'))

users/views.py
from django.shortcuts import render
from django.http import  HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth import logout,login,authenticate
from django.contrib.auth.forms import UserCreationForm
# Create your views here.
def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse('learning_logs:index'))

def register(request):
    error = " "
    if request.method != 'POST':
        form = UserCreationForm()
    else:
        form = UserCreationForm(data=request.POST)

        if form.is_valid():
            new_user = form.save()
            authenticate_user = authenticate(username = new_user.username,password = request.POST['password1'])
            login(request,authenticate_user)
            return HttpResponseRedirect(reverse('learning_logs:index'))
        else:
            error = "注册失败，请重新检查格式。"
    context = {'form':form,'error':error}
    return render(request,'users/register.html',context)

learning_logs/templates/learning_logs/base.html
{% load bootstrap3 %}
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width",initial-scale=1">
    <title>学习笔记</title>
    {% bootstrap_css %}
    {% bootstrap_javascript%}
</head>
<body>
<nav class="navbar navbar-default navbar-static-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed"
            data-toggle="collapse" data-target="#navbar"
            aria-expanded="false" aria-controls="navbar">
            </button>
            <a class="navbar-brand" href="{% url 'learning_logs:index' %}"> 学习笔记 </a>
        </div>

        <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li><a href="{% url 'learning_logs:topics'%}"> 主题 </a></li>
            </ul>

            <ul class="nav navbar-nav navbar-right">
                {% if user.is_authenticated %}
                    <li><a>您好，{{user.username}}。</a></li>
                    <li><a href="{% url 'users:logout' %}"> 注销 </a></li>
                {% else%}
                    <li><a href="{% url 'users:register'%}"> 注册新账户 </a></li>
                    <li><a href="{% url 'users:login' %}"> 登录 </a></li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>
<div class="container">

    <div class="page-header">
        {% block header%}
        {% endblock header%}
    </div>
    <div>
        {% block content%}
        {%endblock content%}
    </div>
</div>
</body>
</html>

learning_logs/templates/learning_logs/edit_entry.html
{% extends "learning_logs/base.html"%}
{% load bootstrap3 %}
{% block header%}
<h2><a href="{% url 'learning_logs:topic' topic.id %}">{{topic}}</a></h2>
{% endblock header%}

{%block content%}
<h3>编辑内容</h3>
<form action="{% url 'learning_logs:edit_entry' topic.id%}" method="post" class="form">
    {% csrf_token%}
    {% bootstrap_form form %}
    <div class="form-group">
            <div>
                <button type="submit" class="btn btn-primary">编辑内容</button>
            </div>
        </div>
</form>
{%endblock content%}

learning_logs/templates/learning_logs/index.html
{%extends "learning_logs/base.html" %}
{% block header %}
    <div class="jumbotron">
        <h1>记录你的学习</h1>
    </div>
{% endblock header%}

{%block content%}
<h2>
    <a href="{% url 'users:register'%}">注册一个账户</a>
    来建立你自己的学习笔记，并列出你正在学习内容的主题。
</h2>
<h2>
    无论何时你学习新的知识的时候，你可以创建一下你学习的内容条目。
</h2>
{%endblock content%}

learning_logs/templates/learning_logs/new_entry.html
{% extends "learning_logs/base.html"%}
{% load bootstrap3 %}
{% block header%}
<h2><a href="{% url 'learning_logs:topic' topic.id%}">{{topic}}</a></h2>
{% endblock header%}
{% block content %}
<h3>新增内容:</h3>
<form action="{%url 'learning_logs:new_entry' topic.id%}" method='post' class="form">
    {%csrf_token%}
    {% bootstrap_form form %}
    <div class="form-group">
            <div>
                <button type="submit" class="btn btn-primary">新增内容</button>
            </div>
        </div>

</form>
{% endblock content %}

learning_logs/templates/learning_logs/new_topic.html
{% extends "learning_logs/base.html"%}
{% load bootstrap3 %}
{% block header%}
<h2>新增一个主题</h2>
{% endblock header%}

{%block content%}
<form action = "{% url 'learning_logs:new_topic'%} " method="post" class="form">
    {%csrf_token%}
    {% bootstrap_form form %}
    <div class="form-group">
            <div>
                <button type="submit" class="btn btn-primary">新增主题</button>
            </div>
        </div>

</form>
{%endblock content%}

learning_logs/templates/learning_logs/topic.html
{% extends 'learning_logs/base.html'%}
{%block header%}
<h2>主题：{{topic}}</h2>
{%endblock header %}

{%block content%}
<h3>内容:</h3>
<p>
    <a href="{%url 'learning_logs:new_entry' topic.id%}">新增内容</a>
</p>
    {%for entry in entries%}
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3>
                {{entry.date_added|date:'M d, Y H:i'}}
                <small>
                       <a href="{% url 'learning_logs:edit_entry' entry.id %}">编辑内容</a>
                </small>
            </h3>
        </div>
        <div class="panel-body">
            {{entry.text|linebreaks}}
        </div>
    </div>
    {%empty%}
        还没有内容~
    {%endfor%}
{%endblock content%}

learning_logs/templates/learning_logs/topics.html
{% extends "learning_logs/base.html"%}
{%block header%}
<h1>主题</h1>
{%endblock header%}
{% block content%}
<ul>
    {% for topic in topics%}
    <li>
        <h3>
            <a href="{% url 'learning_logs:topic' topic.id%}">{{topic}}</a>
        </h3>
    </li>
    {%empty%}
    <li>还没有主题呢</li>
    {%endfor%}
</ul>

<h3><a href="{%url 'learning_logs:new_topic'%}">新增一个主题:</a></h3>
{%endblock content%}

users/templates/users/login.html
{% extends "learning_logs/base.html" %}
{% load bootstrap3 %}
{% block header%}
<h2>请登录您的账户</h2>
{% endblock header%}
{% block content%}
    <form method="post" action="{% url 'users:login'%}" class="form-horizontal">
        {% csrf_token%}
        <div class="form-group">
            <label for="username" class="col-sm-2 control-label">用户名：</label>
            <div class="col-sm-10">
                <input type="text" class="form-control" id="username" name="username" placeholder="请输入用户名">
            </div>
        </div>
        <div class="form-group">
            <label for="password" class="col-sm-2 control-label">密码：</label>
            <div class="col-sm-10">
                <input type="password" class="form-control" id="password" name="password" placeholder="请输入密码">
            </div>
        </div>
        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <button type="submit" class="btn btn-primary">登录</button>
            </div>
        </div>

        <input type="hidden" name="next" value="{% url 'learning_logs:index'%}"/>
    </form>
    {% if form.errors%}
        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <nobr>您的用户名或密码错误，请重新尝试</nobr>
            </div>
        </div>
    {% endif%}
{% endblock content %}

users/templates/users/register.html
{% extends "learning_logs/base.html" %}
{% load bootstrap3 %}
{% block header%}
<h2>注册新账户</h2>
{% endblock header%}
{% block content%}
    <form method="post" action="{% url 'users:register' %}" class="form-horizontal">
        {% csrf_token%}
        <div class="form-group">
            <label for="username" class="col-sm-2 control-label">用户名：</label>
            <div class="col-sm-10">
                <input type="text" class="form-control" id="username" name="username" placeholder="请输入用户名">
            </div>
        </div>
        <div class="form-group">
            <label for="password1" class="col-sm-2 control-label">密码：</label>
            <div class="col-sm-10">
                <input type="password" class="form-control" id="password1" name="password1" placeholder="请输入密码">
            </div>
        </div>
        <div class="form-group">
            <label for="password2" class="col-sm-2 control-label">确认密码：</label>
            <div class="col-sm-10">
                <input type="password" class="form-control" id="password2" name="password2" placeholder="请再次输入密码">
            </div>
        </div>
        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <button type="submit" class="btn btn-primary">注册</button>
            </div>
        </div>
        <!--{%buttons%}-->
        <!--<button name="submit" class="btn btn-primary">注册</button>-->
        <!--{%endbuttons%}-->
        <input type="hidden" name="next" value="{% url 'learning_logs:index'%}"/>
    </form>
    <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                    <p>{{error}}</p>
            </div>
        </div>
{% endblock content %}